<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Item;
use App\Models\ItemFeature;
use App\Models\ItemSpec;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        // Garantiza que existan las categorías necesarias
        $this->call(CategorySeeder::class);

        // Mapa de ítems limpios para Combo 001
        $plan = [
            'luces-cabezales-moviles' => [ // Was luces-moving-head
                ['Cabezal Móvil Beam 7R', 16,
                    ['Lámpara' => '7R 230W', 'Temperatura color' => '8000K', 'Alcance' => '100m', 'Peso' => '17kg'],
                    ['Haz de luz concentrado', 'Colores intensos', 'Movimiento rápido', 'Prisma 8 caras'],
                    'items/beam-light.jpg',
                ],
                ['Cabezal Móvil Híbrido', 8,
                    ['Tipo' => 'Spot / Wash', 'Temperatura color' => 'Ajustable (CTO)', 'Uso' => 'Escenario'],
                    ['Baño de luz cálida (Ambar/Gold)', 'Proyección de texturas suaves', 'Versatilidad total'],
                    'items/spot-light.jpg',
                ],

                ['Cabezal Móvil Beam (Verde)', 8,
                    ['Lámpara' => '7R 230W', 'Color' => 'Verde (Rueda)', 'Uso' => 'Club'],
                    ['Haz sólido de largo alcance', 'Movimientos rápidos para electrónica', 'Color verde intenso'],
                    'items/beam-light.jpg',
                ],
                ['Cabezal Móvil Beam (Gold)', 8,
                    ['Temperatura color' => '3200K (Filtro)', 'Prisma' => '8 caras rotativo', 'Uso' => 'Gala'],
                    ['Color dorado cálido', 'Cruce de haces aéreo', 'Elegante'],
                    'items/beam-light.jpg',
                ],
                ['Cabezal Móvil Beam (Mix Colores)', 8,
                    ['Canales DMX' => '16 canales estándar', 'Función' => 'Strobo 1-13 veces/seg', 'Color' => 'Mix'],
                    ['Barridos rápidos sobre la pista', 'Colores vibrantes mezclados', 'Efecto fiesta'],
                    'items/beam-light.jpg',
                ],

                ['Cabezal Beam (Ámbar)', 8,
                    ['Posición' => 'Piso o Tarimas', 'Enfoque' => 'Electrónico', 'Color' => 'Ámbar'],
                    ['Contraste de color cálido vs fondo frío', 'Efecto de rayos de sol', 'Beam de Piso'],
                    'items/beam-light.jpg',
                ],
                ['Cabezal Móvil Beam (Violeta)', 8,
                    ['Lámpara' => '7R 230W', 'Color' => 'Violeta (Rueda)', 'Uso' => 'Club'],
                    ['Haz sólido de largo alcance', 'Movimientos rápidos', 'Color violeta intenso'],
                    'items/beam-light.jpg',
                ],
                ['Array Iluminación (Beam/Wash)', 12,
                    ['Tipo' => 'Híbrido', 'Uso' => 'Festival', 'Potencia' => 'Alta'],
                    ['Iluminación masiva para grandes escenarios', 'Beam y Wash combinados', 'Main Stage'],
                    'items/beam-light.jpg',
                ],

                ['Cabezal Móvil Wash', 8,
                    ['Lámpara' => 'LED 36x10W / 19x15W', 'Mezcla' => 'RGBW (4 en 1)', 'Zoom' => 'Motorizado 15-60°', 'Modos' => 'DMX / Sound'],
                    ['Baño de color uniforme y potente', 'Ideal para teñir salones completos', 'Movimiento suave y silencioso', 'Efecto Wash'],
                    'items/wash-light.jpg',
                ],
            ],
            'laseres-verde' => [
                ['Láser Verde Pro 3W', 2,
                    ['Potencia' => '3000mW (3W)', 'Color' => 'Verde 532nm', 'Modos' => 'DMX / Audiorítmico'],
                    ['Efecto túnel de alto impacto', 'Ideal para pistas grandes', 'Haz verde de alta visibilidad'],
                    'items/laser-show.jpg',
                ],
                ['Láser Gráfico Verde', 2,
                    ['Potencia' => '1W a 3W Real', 'Escáner' => '25kpps', 'Efectos' => 'Volumétricos'],
                    ['Haces de luz visibles a gran distancia', 'Efectos volumétricos (túneles, planos)', 'Alta definición'],
                    'items/laser-show.jpg',
                ],
                ['Láser Verde (Show)', 2,
                    ['Potencia' => '1000mW - 3000mW', 'Color' => '532nm (Verde puro)', 'Uso' => 'Cruce'],
                    ['Efecto de techo o piso láser', 'Alta visibilidad en ambientes oscuros', 'Split Screen'],
                    'items/laser-show.jpg',
                ],
            ],
            'laseres-azul' => [
                ['Láser Show Azul 3W', 2,
                    ['Potencia' => '3000mW (3W)', 'Color' => 'Azul 445nm', 'Control' => 'ILDA / DMX'],
                    ['Crea túneles y conos de luz sólida', 'Color azul profundo de alta visibilidad', 'Efecto Vortex'],
                    'items/laser-show.jpg',
                ],
                ['Sistema Láser Azul (Túnel)', 2,
                    ['Configuración' => 'Emisor único centrado o par estéreo', 'Seguridad' => 'Zonas de máscara', 'Efecto' => 'Túnel'],
                    ['Crea un cono de luz perfecto alrededor de la persona', 'Ideal para entradas', 'Blue Vortex'],
                    'items/laser-show.jpg',
                ],
            ],
            'escenario-decoracion' => [
                ['Cluster Esferas de Espejos', 12,
                    ['Cantidad' => '12 unidades (aprox)', 'Diámetros' => 'Mix 30cm / 40cm', 'Material' => 'Facetas de vidrio real'],
                    ['Clásico efecto disco vintage', 'Reflejos multidireccionales', 'Montaje en racimo decorativo'],
                    'items/bola-espejo.jpg',
                ],
                ['Arañas de Cristal Estilo Imperio', 6,
                    ['Lámparas' => '12 luces tipo vela (E14)', 'Diámetro' => '80 cm aprox', 'Instalación' => 'Colgado seguro con linga de acero'],
                    ['Aporta elegancia clásica y calidez de gala', 'Cristales facetados de alto brillo real', 'Decoración de lujo'],
                    'items/bola-espejo.jpg',
                ],
                ['Techo de Esferas (Fondo)', 1,
                    ['Cantidad' => 'Alta densidad', 'Uso' => 'Fondo Techo', 'Efecto' => 'Cielo Reflectante'],
                    ['Fondo de esferas masivo', 'Impacto visual', 'Reflejos múltiples'],
                    'items/bola-espejo.jpg',
                ],
                ['Matriz de Esferas de Espejos', 1,
                    ['Cantidad' => '+100 unidades combinadas', 'Soporte' => 'Parrilla Grid estructural', 'Uso' => 'Techo'],
                    ['Impacto visual masivo en el techo', 'Multiplica los haces de luz en miles de puntos', 'Cluster gigante'],
                    'items/bola-espejo.jpg',
                ],
                ['Esferas de Espejos Mix', 10,
                    ['Tamaños' => 'Mix 10cm, 20cm, 30cm', 'Núcleo' => 'Telgopor alta densidad o PVC', 'Material' => 'Espejo real'],
                    ['Combinación de tamaños para dar textura visual', 'Reflexión nítida en todas direcciones', 'Efecto Starburst'],
                    'items/bola-espejo.jpg',
                ],
                ['Hileras de Esferas', 6,
                    ['Disposición' => '6 líneas paralelas', 'Distancia' => '50cm entre esferas', 'Estética' => 'Lineal'],
                    ['Montaje lineal ordenado', 'Túnel de esferas', 'Estética geométrica y moderna'],
                    'items/bola-espejo.jpg',
                ],
                ['Estructura Rectangular de Esferas', 1,
                    ['Formato' => 'Rectángulo de 10m x 4m', 'Densidad' => 'Alta (sin espacios vacíos)', 'Uso' => 'Pista'],
                    ['Define la pista de baile desde el techo', 'Crea un cielo reflectante bajo', 'Impacto visual'],
                    'items/bola-espejo.jpg',
                ],
                ['Arañas Colgantes 5 Brazos', 8,
                    ['Tipo' => 'Araña 5 brazos', 'Altura de montaje' => 'Inferior a las esferas', 'Estilo' => 'Clásico'],
                    ['Elemento de contraste clásico en ambiente moderno', 'Iluminación puntual elegante', 'Complemento decorativo'],
                    'items/bola-espejo.jpg',
                ],
                ['Grid de Esferas', 1,
                    ['Cantidad' => '+80 esferas alineadas', 'Estructura' => 'Truss rectangular perimetral', 'Efecto' => 'Cielo bajo'],
                    ['Techo reflectante continuo', 'Sensación de cielo bajo brillante', 'Impacto rojo'],
                    'items/bola-espejo.jpg',
                ],
                ['Esferas Colgantes', 12,
                    ['Lingas' => 'Acero negro invisible', 'Distribución' => 'Matriz de 8x12', 'Estilo' => 'Ondas'],
                    ['Instalación artística con alturas variables', 'Crea ondas visuales físicas', 'Matrix Wave'],
                    'items/bola-espejo.jpg',
                ],
                ['Matriz Esferas (Techo)', 1,
                    ['Montaje' => 'Grid estructural de aluminio', 'Cantidad' => '+150 esferas', 'Uso' => 'Techo'],
                    ['Cubre todo el techo de la pista principal', 'Multiplica la iluminación fría', 'Impacto masivo'],
                    'items/bola-espejo.jpg',
                ],
                ['Esferas de Espejo (Reflectoras)', 6,
                    ['Tipo' => 'Espejo real alta calidad', 'Uso' => 'Reflexión Láser', 'Posición' => 'Lateral'],
                    ['Reflejan los haces láser creando red', 'Ideales para efecto túnel', 'Blue Vortex'],
                    'items/bola-espejo.jpg',
                ],
                ['Cortina de Esferas', 1,
                    ['Esferas' => 'Diámetro pequeño (10-15cm)', 'Montaje' => 'Tanza o cable de acero fino', 'Estilo' => 'Cortina'],
                    ['Funciona como separador de ambientes', 'Movimiento independiente de cada hilera', 'Backdrop'],
                    'items/bola-espejo.jpg',
                ],
                ['Grid Esferas Masivo', 1,
                    ['Densidad' => 'Muy Alta', 'Forma' => 'Plana', 'Uso' => 'Techo Total'],
                    ['Techo completo de espejos', 'Reflejos infinitos', 'Royal Blue'],
                    'items/bola-espejo.jpg',
                ],
            ],
            'escenario-estructuras' => [
                ['Estructura Truss Negra', 4,
                    ['Material' => 'Aluminio pintado Epoxy', 'Medida' => 'Tramos de 2m y 3m', 'Color' => 'Negro'],
                    ['Soporte sólido y estético en negro', 'Montaje modular adaptable', 'Ideal para pórticos'],
                    'items/estructura-truss.jpg',
                ],
                ['Truss Circular (Ring)', 2,
                    ['Diámetro' => '4 a 6 metros', 'Material' => 'Aluminio 6082 T6', 'Uso' => 'Central'],
                    ['Punto focal central para pistas de baile', 'Permite iluminación 360 grados', 'Estructura circular'],
                    'items/estructura-truss.jpg',
                ],
                ['Tarimas / Escenario DJ', 1,
                    ['Material' => 'Modular', 'Altura' => 'Ajustable', 'Uso' => 'DJ'],
                    ['Plataforma elevada para el artista', 'Soporte robusto', 'Escenario'],
                    'items/tarima.jpg',
                ],
                ['Estructura Escenario (Layher)', 1,
                    ['Ancho de boca' => '+15 metros', 'Capacidad de carga' => 'Toneladas', 'Tipo' => 'Layher'],
                    ['Soporte para grandes cargas y alturas', 'Sistema modular industrial seguro', 'Festival'],
                    'items/estructura-truss.jpg',
                ],
                ['Bastidor / Estructura Móvil', 1,
                    ['Tipo' => 'Móvil con ruedas', 'Material' => 'Metal negro', 'Uso' => 'Soporte Cortina'],
                    ['Estructura soporte para backdrop', 'Fácil desplazamiento', 'Cortina Esferas'],
                    'items/estructura-truss.jpg',
                ],
            ],
            'luces-neon' => [
                ['Círculo LED Neon Flex', 2,
                    ['Diámetro' => '3 metros (aprox)', 'Tecnología' => 'Tira LED Flex IP65', 'Uso' => 'Piso'],
                    ['Delimitación de área para performance', 'Luz continua sin puntos visibles', 'Efecto visual impactante'],
                    'items/pista-led.jpg',
                ],
                ['Tubos LED Verticales', 8,
                    ['Tipo' => 'Tubo Pixel o Neon Flex Rígido', 'Altura' => '2 a 3 metros', 'Estética' => 'Cyberpunk'],
                    ['Delimitan el espacio verticalmente', 'Estética moderna lineal', 'Sky Diamond'],
                    'items/efecto-led.jpg',
                ],
            ],
            'luces-pixel' => [
                ['Tubos LED Pixel', 8,
                    ['Longitud' => '1 metro por tubo', 'Colores' => 'RGBW + Ámbar', 'Autonomía' => '20 horas máx'],
                    ['Efectos de mapeo pixel por pixel', 'Totalmente inalámbricos (batería)', 'Tipo Astera/Titan'],
                    'items/efecto-led.jpg',
                ],
            ],
            'luces-banadores' => [
                ['Bañadores LED', 6,
                    ['Tipo' => 'Barra LED', 'Colores' => 'RGBW', 'Control' => 'DMX'],
                    ['Luz de base uniforme', 'Ideal para teñir espacios', 'Alta potencia'],
                    'items/wash-light.jpg',
                ],
                ['Bañadores LED High Power', 12,
                    ['Chip LED' => '4-in-1 (RGBW)', 'Apertura' => '45 grados (Wash)', 'Colores' => 'Full Red'],
                    ['Saturación de color total', 'Cobertura amplia sin sombras duras', 'Red Lounge'],
                    'items/wash-light.jpg',
                ],
            ],
            'efectos-niebla' => [
                ['Máquina de Humo Haze', 2,
                    ['Tipo' => 'Haze (Niebla)', 'Consumo' => 'Líquido base agua', 'Control' => 'DMX / Remoto'],
                    ['Niebla constante y fina', 'Realza haces de luz', 'Sin olor residual'],
                    'items/maquina-humo.jpg',
                ],
            ],
            'efectos-fuego-frio' => [
                ['Máquina Fuego Frío', 4,
                    ['Altura chispa' => 'Regulable 1 a 5 metros', 'Consumo' => 'Polvo de Titanio', 'Control' => 'DMX 512'],
                    ['Efecto pirotécnico seguro para interiores', 'No genera humo ni olor', 'Sparkulars'],
                    'items/confetti.jpg',
                ],
            ],
            'pantallas-verticales' => [
                ['Pantalla LED Póster', 4,
                    ['Pitch' => 'P3.9 Indoor', 'Medidas' => '0.5m x 2.5m (por columna)', 'Resolución' => 'Alta Definición'],
                    ['Formato vertical tipo tótem', 'Alta definición para fotos y gráficas', 'Diseño delgado'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantalla LED Tótem 1x4', 4,
                    ['Configuración' => 'Pitch 3.9mm', 'Formato' => 'Tótems de 1m x 4m', 'Uso' => 'Escenografía'],
                    ['Diseño en columnas separadas', 'Ideal para loops verticales', 'Gran escala'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantallas LED Tótems (Separadas)', 6,
                    ['Configuración' => '4 a 6 columnas independientes', 'Bases' => 'Soportes de piso estables', 'Estilo' => 'Separado'],
                    ['Permite ver profundidad', 'Diseño aireado y moderno', 'Blue Winter'],
                    'items/pantalla-led.jpg',
                ],
            ],
            'pantallas-led-interior' => [ // Was pantallas-led-indoor
                ['Pantalla LED P3 Indoor', 6,
                    ['Paso de pixel' => 'P3.9', 'Uso' => 'Indoor', 'Brillo (nits)' => '1000', 'Resolución' => 'Full HD'],
                    ['Módulos escalables', 'Incluye procesador', 'Instalación profesional', 'Ideal para eventos'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantalla LED de Fondo', 1,
                    ['Configuración' => '6 columnas de 1x3m', 'Resolución' => 'Full HD escalable', 'Uso' => 'Fondo Escenario'],
                    ['Diseño segmentado en columnas', 'Brillo ajustable para cámara', 'Curvo/Segmentado'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantalla LED Segmentada', 1,
                    ['Módulos' => '5 columnas independientes', 'Pixel Pitch' => 'P3 Indoor', 'Transparencia' => 'Visual'],
                    ['Montaje en tiras separadas', 'Permite ver el fondo o estructura', 'Diseño moderno'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantalla LED P3 Split', 2,
                    ['Resolución' => '1920Hz Refresh Rate', 'Configuración' => '2 pantallas de 3x2m', 'Uso' => 'Lateral'],
                    ['Alta resolución para textos finos', 'Brillo calibrado para no saturar', 'Ideal bodas'],
                    'items/pantalla-led.jpg',
                ],
                ['Pantalla LED Escenario Completo', 1,
                    ['Dimensión' => 'Panorámica (ej: 8m x 3m)', 'Conexión' => 'Procesador de video escalador', 'Uso' => 'Fondo Total'],
                    ['Fondo escenográfico total', 'Muestra gráficas temáticas', 'Alto impacto visual'],
                    'items/pantalla-led.jpg',
                ],
            ],
            'laseres-rojo' => [
                ['Sistema Láser Array Rojo', 2,
                    ['Potencia' => 'Banco de 6 salidas x 500mW', 'Longitud de onda' => '638nm (Rojo)', 'Modos' => 'Barrido, Túnel, Lluvia'],
                    ['Crea una red de luz (web effect)', 'Color rojo intenso de alta saturación', 'Array multipunto'],
                    'items/laser-show.jpg',
                ],
            ],
            'luces-control' => [
                ['Consola de Iluminación', 1,
                    ['Protocolo' => 'DMX512 / ArtNet', 'Canales' => '2048 canales o superior', 'Uso' => 'Control'],
                    ['Control total de cenas y movimientos', 'Capacidad para gestionar shows complejos', 'Profesional'],
                    'items/sonido.jpg',
                ],
            ],
            'efectos-co2' => [
                ['Pistola de CO2', 2,
                    ['Alcance' => '6 a 8 metros', 'Insumo' => 'Tubo de gas CO2 líquido', 'Operación' => 'Manual (gatillo)'],
                    ['Dispara chorros de niebla helada', 'Efecto refrescante y visual', 'Pistola Cryo Gun'],
                    'items/co2.jpg',
                ],
            ],
            'efectos-varios' => [
                ['Cotillón Luminoso', 100,
                    ['Alimentación' => 'Pilas AA / Botón', 'Material' => 'Látex/Plástico transparente', 'Tipo' => 'Globos/Varitas'],
                    ['Elementos participativos para el público', 'Globos transparentes con tira LED', 'Fiesta'],
                    'items/confetti.jpg',
                ],
            ],
            'pantallas-techo' => [
                ['Paneles LED Techo', 20,
                    ['Módulos' => 'Cuadrados de 1x1m o 0.5x0.5m', 'Peso' => 'Liviano (Magnesio)', 'Uso' => 'Techo'],
                    ['Crea una atmósfera inmersiva sobre la pista', 'Efectos visuales mapeables y dinámicos', 'Digital Sky'],
                    'items/pantallas-led.jpg',
                ],
                ['Techo LED Pixel', 1,
                    ['Conexión' => 'Sending Card + Receiving Cards', 'Contenido' => 'Video', 'Brillo' => 'Alto'],
                    ['Contenido de video reproducido en el techo', 'Alta luminosidad y contraste', 'Pixel Amber'],
                    'items/pantallas-led.jpg',
                ],
                ['Paneles LED Techo (Diamante)', 12,
                    ['Módulos' => '50x50cm o 1x1m configurables', 'Rigging' => 'Puntos de colgado independientes', 'Forma' => 'Rombo'],
                    ['Montaje aéreo en forma de rombos', 'Genera un techo digital dinámico', 'Sky Diamond'],
                    'items/pantallas-led.jpg',
                ],
                ['Pantalla LED Techo (Inclinada)', 1,
                    ['Rigging' => 'Motores con angulación variable', 'Gabinete' => 'Liviano con lock rápido', 'Uso' => 'Overhead'],
                    ['Genera un techo visual sobre el artista', 'Ángulo agresivo para mayor impacto', 'DJ Booth'],
                    'items/pantallas-led.jpg',
                ],
            ],
            'pantallas-diseno' => [
                ['Pantallas LED Diseño', 4,
                    ['Pitch' => 'P2.5 o P3 Indoor', 'Brillo' => '1000 nits ajustable', 'Forma' => 'Curva/Ondas'],
                    ['Montaje no tradicional', 'Integra la tecnología con la decoración', 'Gold Waves'],
                    'items/pantalla-led-curva.jpg',
                ],
                ['Pantalla LED Dividida (Stripes)', 2,
                    ['Módulos' => '3 franjas horizontales por lado', 'Soporte' => 'Torres truss laterales', 'Estilo' => 'Persiana'],
                    ['Diseño aireado que deja ver atrás', 'Permite efectos creativos de barrido', 'Split Screen'],
                    'items/pantalla-led.jpg',
                ],
                ['Mix Pantallas Custom', 1,
                    ['Procesamiento' => 'Múltiples salidas 4K', 'Formas' => 'Circulares y rectangulares', 'Diseño' => 'Multicapa'],
                    ['Diseño multicapa con profundidad', 'Combina formas circulares y rectangulares', 'Festival'],
                    'items/pantalla-led.jpg',
                ],
            ],
            'escenario-rigging' => [
                ['Sistema de Rigging', 1,
                    ['Motores' => '1 tonelada / 500kg', 'Truss' => 'Cuadrada 30x30', 'Seguridad' => 'Certificada'],
                    ['Seguridad certificada para cargas suspendidas', 'Permite elevar la estructura completa', 'Profesional'],
                    'items/estructura-truss.jpg',
                ],
            ],
            'luces-ambientacion' => [
                ['Iluminación Perimetral', 20,
                    ['Equipos' => 'Par LED inalámbricos (batería)', 'Autonomía' => '8-10 horas', 'Uso' => 'Paredes/Mesas'],
                    ['Colorea las paredes y mesas del salón', 'Crea la base de color del evento', 'Sin cables'],
                    'items/wash-light.jpg',
                ],
                ['Iluminación Wash Azul', 6,
                    ['Color' => 'Azul Royal / UV', 'Zoom' => 'Motorizado', 'Uso' => 'Ambientación'],
                    ['Clima frío/elegante', 'Luz suave que baña sin encandilar', 'Wash Spot'],
                    'items/wash-light.jpg',
                ],
                ['Iluminación Beam Cruzada', 8,
                    ['Posición' => 'Perimetral o desde escenario', 'Enfoque' => 'Aéreo', 'Efecto' => 'Cruce'],
                    ['Haces de luz que atraviesan el salón', 'Genera atmósfera de gran evento', 'Royal Blue'],
                    'items/beam-light.jpg',
                ],
            ],
            'escenario-pisos' => [
                ['Pista Ajedrezada', 1,
                    ['Módulos' => 'Placas de 1x1m', 'Acabado' => 'Vinilo alto tránsito / Acrílico', 'Estilo' => 'Ajedrez'],
                    ['Piso clásico para baile', 'Superficie lisa y nivelada', 'Blanco y Negro'],
                    'items/pista-led.jpg',
                ],
            ],
            'pantallas-gran-formato' => [
                ['Pared LED Gran Formato', 1,
                    ['Medidas' => '10m ancho x 4m alto (aprox)', 'Resolución' => '4K Ready', 'Uso' => 'Cinema'],
                    ['Inmersión total con imágenes de paisaje', 'Fondo escenográfico de alto impacto visual', 'Cinema Wall'],
                    'items/pantalla-led.jpg',
                ],
            ],
            'pantallas-decoracion' => [
                ['Letras Corpóreas LED (LOVE)', 1,
                    ['Altura' => '2 metros (aprox)', 'Pixel Pitch' => 'P3 / P4 Outdoor', 'Estructura' => 'Auto-portante'],
                    ['Cartelera gigante personalizable con video', 'Ideal para recepciones y fotos', 'Signo LOVE'],
                    'items/pantalla-led.jpg',
                ],
            ],
            'luces-decorativa' => [
                ['Iluminación Decorativa (Guirnaldas)', 10,
                    ['Tipo' => 'Kermesse / Guirnalda', 'Luz' => 'Cálida', 'Uso' => 'Ambientación'],
                    ['Iluminación cálida y romántica', 'Aporta detalle estético', 'LOVE Sign'],
                    'items/bola-espejo.jpg',
                ],
                ['Arañas de Estilo (Chandelier)', 6,
                    ['Lámparas' => 'Cálidas dimerizables', 'Estilo' => 'Clásico', 'Montaje' => 'Colgante'],
                    ['Contraste clásico vs tecnológico', 'Aporta lujo y altura al diseño', 'Cold Chandelier'],
                    'items/bola-espejo.jpg',
                ],
                ['Pin Spot LED Beam', 12,
                    ['Ángulo de apertura' => '2 a 4 grados', 'Color' => 'Ámbar / Blanco Cálido', 'Tecnología' => 'LED'],
                    ['Genera el rebote de luz intenso', 'Haz muy cerrado para golpear esferas', 'Efecto Starburst'],
                    'items/beam-light.jpg',
                ],
            ],
        ];

        // $migrationItems removido ya que limpiamos todo.
        // $plan = array_merge_recursive($plan, $migrationItems); // ya no es necesario

        foreach ($plan as $categorySlug => $items) {
            $category = Category::where('slug', $categorySlug)->first();

            if (! $category) {
                // Fail-fast (opcional): avisar y cortar
                $this->command?->error("Falta la categoría requerida: {$categorySlug}. Revisá CategorySeeder.");
                throw new \RuntimeException("Falta la categoría {$categorySlug}");
            }

            foreach ($items as [$name, $stock, $specs, $features, $imageUrl]) {
                $slug = Str::slug($name);

                // Ítem idempotente por slug
                $item = Item::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'category_id' => $category->id,
                        'name' => $name,
                        'description' => $name.' — equipo en excelente estado para eventos.',
                        'image_url' => 'storage/items/'.$slug.'.jpg',
                        'stock' => $stock,
                        'active' => true,
                    ]
                );

                // Features idempotentes por (item_id, sort_order)
                $order = 10;
                foreach ($features as $text) {
                    ItemFeature::updateOrCreate(
                        ['item_id' => $item->id, 'sort_order' => $order],
                        ['text' => $text]
                    );
                    $order += 10;
                }

                // Specs idempotentes por (item_id, spec_key)
                $order = 10;
                foreach ($specs as $k => $v) {
                    ItemSpec::updateOrCreate(
                        ['item_id' => $item->id, 'spec_key' => $k],
                        ['spec_value' => $v, 'sort_order' => $order]
                    );
                    $order += 10;
                }
            }
        }
    }
}
