; Configuración PHP para Laravel 12 en Azure
error_log = /dev/stderr
display_errors = Off
log_errors = On
display_startup_errors = Off
date.timezone = America/Argentina/Cordoba  ; Cambia por tu zona
memory_limit = 256M